# 6CS012 - Worksheet 0
## A Tutorial and Assessment on Python and NumPy for Deep Learning
**Module Leader:** Siman Giri

---
# Section 4: TO-DO Tasks
## 4.1 Exercise on Functions

### Task 1: Unit Converter
> Run this cell. It will prompt you to choose a conversion type and enter a value.

In [1]:
def convert_length(value, direction):
    if direction == '1':
        result = value * 3.28084
        print(f"  Result: {value} m = {result:.4f} ft")
    elif direction == '2':
        result = value / 3.28084
        print(f"  Result: {value} ft = {result:.4f} m")
    else:
        raise ValueError("Invalid direction. Choose '1' or '2'.")
    return result


def convert_weight(value, direction):
    if direction == '1':
        result = value * 2.20462
        print(f"  Result: {value} kg = {result:.4f} lbs")
    elif direction == '2':
        result = value / 2.20462
        print(f"  Result: {value} lbs = {result:.4f} kg")
    else:
        raise ValueError("Invalid direction. Choose '1' or '2'.")
    return result


def convert_volume(value, direction):
    if direction == '1':
        result = value * 0.264172
        print(f"  Result: {value} L = {result:.4f} gal")
    elif direction == '2':
        result = value / 0.264172
        print(f"  Result: {value} gal = {result:.4f} L")
    else:
        raise ValueError("Invalid direction. Choose '1' or '2'.")
    return result


def unit_converter():
    print("=" * 40)
    print("         UNIT CONVERTER")
    print("=" * 40)
    print("Choose conversion type:")
    print("  1. Length  (m <-> ft)")
    print("  2. Weight  (kg <-> lbs)")
    print("  3. Volume  (L <-> gal)")

    try:
        conv_type = input("\nEnter choice (1/2/3): ").strip()

        if conv_type == '1':
            print("\n  Length options:")
            print("    1. Meters  ->  Feet")
            print("    2. Feet    ->  Meters")
            direction = input("  Enter direction (1/2): ").strip()
            value = float(input("  Enter value: "))
            return convert_length(value, direction)

        elif conv_type == '2':
            print("\n  Weight options:")
            print("    1. Kilograms  ->  Pounds")
            print("    2. Pounds     ->  Kilograms")
            direction = input("  Enter direction (1/2): ").strip()
            value = float(input("  Enter value: "))
            return convert_weight(value, direction)

        elif conv_type == '3':
            print("\n  Volume options:")
            print("    1. Liters   ->  Gallons")
            print("    2. Gallons  ->  Liters")
            direction = input("  Enter direction (1/2): ").strip()
            value = float(input("  Enter value: "))
            return convert_volume(value, direction)

        else:
            print("Invalid choice. Please enter 1, 2, or 3.")
            return None

    except ValueError as e:
        print(f"Error: Invalid input — {e}")
        return None

unit_converter()


         UNIT CONVERTER
Choose conversion type:
  1. Length  (m <-> ft)
  2. Weight  (kg <-> lbs)
  3. Volume  (L <-> gal)

Enter choice (1/2/3): 1

  Length options:
    1. Meters  ->  Feet
    2. Feet    ->  Meters
  Enter direction (1/2): 1
  Enter value: 50
  Result: 50.0 m = 164.0420 ft


164.042

### Task 2: Mathematical Operations on a List of Numbers
> Run this cell. It will prompt you to choose an operation and enter numbers.

In [4]:
def compute_sum(numbers):
    if not numbers:
        raise ValueError("List is empty. Please provide at least one number.")
    total = 0
    for n in numbers:
        total += n
    return total


def compute_average(numbers):
    if not numbers:
        raise ValueError("List is empty. Please provide at least one number.")
    return compute_sum(numbers) / len(numbers)


def compute_maximum(numbers):
    if not numbers:
        raise ValueError("List is empty. Please provide at least one number.")
    max_val = numbers[0]
    for n in numbers:
        if n > max_val:
            max_val = n
    return max_val


def compute_minimum(numbers):
    if not numbers:
        raise ValueError("List is empty. Please provide at least one number.")
    min_val = numbers[0]
    for n in numbers:
        if n < min_val:
            min_val = n
    return min_val


def math_operations():
    print("=" * 40)
    print("      MATHEMATICAL OPERATIONS")
    print("=" * 40)
    print("Choose an operation:")
    print("  1. Sum")
    print("  2. Average")
    print("  3. Maximum")
    print("  4. Minimum")

    try:
        choice = input("\nEnter choice (1/2/3/4): ").strip()
        raw = input("Enter numbers separated by spaces (e.g. 3 7 2 9 4): ").strip()

        if not raw:
            raise ValueError("No numbers were entered.")

        numbers = [float(x) for x in raw.split()]
        print(f"\nNumbers entered: {numbers}")

        if choice == '1':
            result = compute_sum(numbers)
            print(f"Sum     = {result}")
        elif choice == '2':
            result = compute_average(numbers)
            print(f"Average = {result:.4f}")
        elif choice == '3':
            result = compute_maximum(numbers)
            print(f"Maximum = {result}")
        elif choice == '4':
            result = compute_minimum(numbers)
            print(f"Minimum = {result}")
        else:
            print("Invalid choice. Please enter 1, 2, 3, or 4.")
            return None

        return result

    except ValueError as e:
        print(f"Error: Invalid input — {e}")
        return None

math_operations()


      MATHEMATICAL OPERATIONS
Choose an operation:
  1. Sum
  2. Average
  3. Maximum
  4. Minimum

Enter choice (1/2/3/4): 1
Enter numbers separated by spaces (e.g. 3 7 2 9 4): 32 34

Numbers entered: [32.0, 34.0]
Sum     = 66.0


66.0

---
## 4.2 Exercise on List Manipulation
> Each cell defines a function, then prompts you interactively for input.

#### 1. Extract Every Other Element

In [6]:
def extract_every_other(lst):
    return lst[::2]
try:
    raw = input("Enter a list of numbers separated by spaces: ").strip()
    lst = [int(x) for x in raw.split()]
    result = extract_every_other(lst)
    print(f"Input : {lst}")
    print(f"Output: {result}")
except ValueError:
    print("Error: Please enter valid integers separated by spaces.")


Enter a list of numbers separated by spaces: 1 2 3 4 5 6
Input : [1, 2, 3, 4, 5, 6]
Output: [1, 3, 5]


#### 2. Slice a Sublist

In [7]:
def get_sublist(lst, start, end):
    return lst[start:end + 1]''
try:
    raw = input("Enter a list of numbers separated by spaces: ").strip()
    lst = [int(x) for x in raw.split()]
    start = int(input("Enter start index: "))
    end   = int(input("Enter end index  : "))
    result = get_sublist(lst, start, end)
    print(f"Input : {lst}, start={start}, end={end}")
    print(f"Output: {result}")
except ValueError:
    print("Error: Please enter valid integers.")


Enter a list of numbers separated by spaces: 1 2 3 4 5 6
Enter start index: 2
Enter end index  : 4
Input : [1, 2, 3, 4, 5, 6], start=2, end=4
Output: [3, 4, 5]


#### 3. Reverse a List Using Slicing

In [8]:
def reverse_list(lst):
    return lst[::-1]
try:
    raw = input("Enter a list of numbers separated by spaces: ").strip()
    lst = [int(x) for x in raw.split()]
    result = reverse_list(lst)
    print(f"Input : {lst}")
    print(f"Output: {result}")
except ValueError:
    print("Error: Please enter valid integers separated by spaces.")


Enter a list of numbers separated by spaces: 1 2 3 4 5
Input : [1, 2, 3, 4, 5]
Output: [5, 4, 3, 2, 1]


#### 4. Remove the First and Last Elements

In [9]:
def remove_first_last(lst):
    return lst[1:-1]
try:
    raw = input("Enter a list of numbers separated by spaces: ").strip()
    lst = [int(x) for x in raw.split()]
    if len(lst) < 2:
        print("Error: List must have at least 2 elements.")
    else:
        result = remove_first_last(lst)
        print(f"Input : {lst}")
        print(f"Output: {result}")
except ValueError:
    print("Error: Please enter valid integers separated by spaces.")


Enter a list of numbers separated by spaces: 1 2 3 4 5
Input : [1, 2, 3, 4, 5]
Output: [2, 3, 4]


#### 5. Get the First n Elements

In [10]:
def get_first_n(lst, n):
    return lst[:n]

try:
    raw = input("Enter a list of numbers separated by spaces: ").strip()
    lst = [int(x) for x in raw.split()]
    n   = int(input("Enter n (how many elements from the start): "))
    result = get_first_n(lst, n)
    print(f"Input : {lst}, n={n}")
    print(f"Output: {result}")
except ValueError:
    print("Error: Please enter valid integers.")


Enter a list of numbers separated by spaces: 1 2 3 4 5
Enter n (how many elements from the start): 3
Input : [1, 2, 3, 4, 5], n=3
Output: [1, 2, 3]


#### 6. Extract Elements from the End

In [11]:
def get_last_n(lst, n):
    return lst[-n:]
try:
    raw = input("Enter a list of numbers separated by spaces: ").strip()
    lst = [int(x) for x in raw.split()]
    n   = int(input("Enter n (how many elements from the end): "))
    result = get_last_n(lst, n)
    print(f"Input : {lst}, n={n}")
    print(f"Output: {result}")
except ValueError:
    print("Error: Please enter valid integers.")


Enter a list of numbers separated by spaces: 1 2 3 4 5
Enter n (how many elements from the end): 2
Input : [1, 2, 3, 4, 5], n=2
Output: [4, 5]


#### 7. Extract Elements in Reverse Order (every second from second-to-last)

In [12]:
def reverse_skip(lst):
    return lst[-2::-2]

try:
    raw = input("Enter a list of numbers separated by spaces: ").strip()
    lst = [int(x) for x in raw.split()]
    result = reverse_skip(lst)
    print(f"Input : {lst}")
    print(f"Output: {result}")
except ValueError:
    print("Error: Please enter valid integers separated by spaces.")


Enter a list of numbers separated by spaces: 1 2 3 4 5 6
Input : [1, 2, 3, 4, 5, 6]
Output: [5, 3, 1]


---
## 4.3 Exercise on Nested Lists
> Each cell defines a function and tests it with the example from the worksheet.

#### 1. Flatten a Nested List

In [13]:
def flatten(lst):
    result = []
    for sublist in lst:
        for item in sublist:
            result.append(item)
    return result


# Example
inp = [[1, 2], [3, 4], [5]]
print(f"Input : {inp}")
print(f"Output: {flatten(inp)}")   # Expected: [1, 2, 3, 4, 5]


Input : [[1, 2], [3, 4], [5]]
Output: [1, 2, 3, 4, 5]


#### 2. Accessing Nested List Elements

In [14]:
def access_nested_element(lst, indices):
    element = lst
    for idx in indices:
        element = element[idx]
    return element
lst     = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
print(f"Input : lst={lst}, indices={indices}")
print(f"Output: {access_nested_element(lst, indices)}")   # Expected: 6


Input : lst=[[1, 2, 3], [4, 5, 6], [7, 8, 9]], indices=[1, 2]
Output: 6


#### 3. Sum of All Elements in a Nested List

In [16]:
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

inp = [[1, 2], [3, [4, 5]], 6]
print(f"Input : {inp}")
print(f"Output: {sum_nested(inp)}")   # Expected: 21


Input : [[1, 2], [3, [4, 5]], 6]
Output: 21


#### 4. Remove Specific Element from a Nested List

In [18]:
def remove_element(lst, elem):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result
lst  = [[1, 2], [3, 2], [4, 5]]
elem = 2
print(f"Input : lst={lst}, elem={elem}")
print(f"Output: {remove_element(lst, elem)}")


Input : lst=[[1, 2], [3, 2], [4, 5]], elem=2
Output: [[1], [3], [4, 5]]


#### 5. Find the Maximum Element in a Nested List

In [19]:
def find_max(lst):
    max_val = None
    for item in lst:
        candidate = find_max(item) if isinstance(item, list) else item
        if max_val is None or candidate > max_val:
            max_val = candidate
    return max_val
inp = [[1, 2], [3, [4, 5]], 6]
print(f"Input : {inp}")
print(f"Output: {find_max(inp)}")   # Expected: 6


Input : [[1, 2], [3, [4, 5]], 6]
Output: 6


#### 6. Count Occurrences of an Element in a Nested List

In [20]:
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count
lst  = [[1, 2], [2, 3], [2, 4]]
elem = 2
print(f"Input : lst={lst}, elem={elem}")
print(f"Output: {count_occurrences(lst, elem)}")


Input : lst=[[1, 2], [2, 3], [2, 4]], elem=2
Output: 3


#### 7. Flatten a List of Lists of Lists (any depth)

In [21]:
def deep_flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

inp = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print(f"Input : {inp}")
print(f"Output: {deep_flatten(inp)}")


Input : [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
Output: [1, 2, 3, 4, 5, 6, 7, 8]


#### 8. Nested List Average

In [22]:
def average_nested(lst):
    flat = deep_flatten(lst)
    return sum(flat) / len(flat)
inp = [[1, 2], [3, 4], [5, 6]]
print(f"Input : {inp}")
print(f"Output: {average_nested(inp)}")

Input : [[1, 2], [3, 4], [5, 6]]
Output: 3.5


---
# Section 10: TO-DO NumPy
## 10.1 Basic Vector and Matrix Operations with NumPy

In [23]:
import numpy as np

### Problem 1: Array Creation

In [24]:
# 1. Empty array of size 2x2
empty_2x2 = np.empty((2, 2))
print("1. Empty 2x2 array:")
print(empty_2x2)
print()

# 2. All-ones array of size 4x2
ones_4x2 = np.ones((4, 2))
print("2. All-ones 4x2 array:")
print(ones_4x2)
print()

# 3. Array filled with a specific fill_value using np.full
filled = np.full((3, 3), fill_value=7)
print("3. 3x3 array filled with 7 (np.full):")
print(filled)
print()

# 4. Zeros array with same shape as a given array (np.zeros_like)
reference = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_arr = np.zeros_like(reference)
print("4. np.zeros_like — same shape as reference array:")
print(zeros_like_arr)
print()

# 5. Ones array with same shape as a given array (np.ones_like)
ones_like_arr = np.ones_like(reference)
print("5. np.ones_like — same shape as reference array:")
print(ones_like_arr)
print()

# 6. Convert a Python list to a NumPy array
new_list = [1, 2, 3, 4]
np_from_list = np.array(new_list)
print("6. Python list [1,2,3,4] converted to NumPy array:")
print(np_from_list)


1. Empty 2x2 array:
[[1.69682962e-315 0.00000000e+000]
 [6.36601982e-314 1.65080166e-315]]

2. All-ones 4x2 array:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. 3x3 array filled with 7 (np.full):
[[7 7 7]
 [7 7 7]
 [7 7 7]]

4. np.zeros_like — same shape as reference array:
[[0 0 0]
 [0 0 0]]

5. np.ones_like — same shape as reference array:
[[1 1 1]
 [1 1 1]]

6. Python list [1,2,3,4] converted to NumPy array:
[1 2 3 4]


### Problem 2: Array Manipulation — Numerical Ranges and Indexing

In [25]:
# 1. Array with values ranging from 10 to 49
arr_range = np.arange(10, 50)
print("1. Array with values 10 to 49 (np.arange):")
print(arr_range)
print()

# 2. 3x3 matrix with values 0 to 8 using reshape
matrix_3x3 = np.arange(9).reshape(3, 3)
print("2. 3x3 matrix with values 0 to 8 (reshape):")
print(matrix_3x3)
print()

# 3. 3x3 identity matrix
identity = np.eye(3)
print("3. 3x3 Identity matrix (np.eye):")
print(identity)
print()

# 4. Random array of size 30 — find the mean
rand_30 = np.random.random(30)
print("4. Random array of size 30:")
print(rand_30)
print(f"   Mean = {rand_30.mean():.4f}")
print()

# 5. 10x10 random array — find min and max
rand_10x10 = np.random.random((10, 10))
print("5. 10x10 random array (first 3 rows shown):")
print(rand_10x10[:3])
print(f"   Min = {rand_10x10.min():.4f}")
print(f"   Max = {rand_10x10.max():.4f}")
print()

# 6. Zero array of size 10 — replace 5th element with 1
zero_arr = np.zeros(10)
zero_arr[4] = 1    # index 4 is the 5th element (0-based)
print("6. Zero array of size 10 with 5th element set to 1:")
print(zero_arr)
print()

# 7. Reverse an array
arr = np.array([1, 2, 0, 0, 4, 0])
print("7. Original array:", arr)
print("   Reversed      :", arr[::-1])
print()

# 8. 2D array with 1 on border and 0 inside
border = np.ones((6, 6), dtype=int)
border[1:-1, 1:-1] = 0
print("8. 6x6 array with 1 on border and 0 inside:")
print(border)
print()

# 9. 8x8 checkerboard pattern
checker = np.zeros((8, 8), dtype=int)
checker[1::2, ::2] = 1   # odd rows, even cols
checker[::2, 1::2] = 1   # even rows, odd cols
print("9. 8x8 Checkerboard pattern:")
print(checker)


1. Array with values 10 to 49 (np.arange):
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix with values 0 to 8 (reshape):
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 Identity matrix (np.eye):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array of size 30:
[0.88968077 0.24029781 0.95194239 0.36217182 0.80151674 0.30882161
 0.3256037  0.43825947 0.90762232 0.50444892 0.53123832 0.56573868
 0.00710125 0.97482114 0.09650642 0.06182351 0.34749269 0.89617476
 0.09155158 0.2389464  0.61982851 0.77520357 0.10541325 0.93383247
 0.82858191 0.29984869 0.2364881  0.39500765 0.1117434  0.65091923]
   Mean = 0.4833

5. 10x10 random array (first 3 rows shown):
[[0.76172442 0.50041092 0.36000767 0.15199189 0.68691142 0.17655833
  0.79803216 0.11624873 0.80274524 0.1706914 ]
 [0.54147852 0.55560561 0.25186289 0.55933905 0.63112417 0.63330224
  0.7170294  0.99640353 0.98661855 0.17004546]
 [0.78383654 0.84014778 0.3088530

### Problem 3: Array Operations

In [26]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print("Given arrays:")
print(f"x =\n{x}\n")
print(f"y =\n{y}\n")
print(f"v = {v}")
print(f"w = {w}\n")
print("-" * 35)

# 1. Add
print("1. x + y =")
print(x + y)
print()

# 2. Subtract
print("2. x - y =")
print(x - y)
print()

# 3. Multiply with integer
scalar = 3
print(f"3. x * {scalar} =")
print(x * scalar)
print()

# 4. Square of each element
print("4. Square of each element of x (np.square):")
print(np.square(x))
print()

# 5. Dot products
print("5a. Dot product v · w =", np.dot(v, w))
print()
print("5b. Dot product x · v =")
print(np.dot(x, v))
print()
print("5c. Dot product x · y =")
print(np.dot(x, y))
print()

# 6. Concatenations
print("6a. Concatenate x and y along rows (axis=0 / vstack):")
print(np.concatenate((x, y), axis=0))
print()
print("6b. Concatenate v and w along column (column_stack):")
print(np.column_stack((v, w)))
print()

# 7. Concatenate x and v — demonstrate error and explain
print("7. Trying np.concatenate((x, v))...")
try:
    np.concatenate((x, v))
except ValueError as e:
    print(f"   ValueError: {e}")
    print()
    print("   WHY: x has shape", x.shape, "(2D) but v has shape", v.shape, "(1D).")
    print("   np.concatenate() requires ALL arrays to have the same number of dimensions.")
    print("   Since x is 2-dimensional and v is 1-dimensional, they are incompatible.")
    print()
    print("   FIX: reshape v to (1, 2) first, then concatenate along axis=0:")
    fixed = np.concatenate((x, v.reshape(1, 2)), axis=0)
    print(fixed)


Given arrays:
x =
[[1 2]
 [3 5]]

y =
[[5 6]
 [7 8]]

v = [ 9 10]
w = [11 12]

-----------------------------------
1. x + y =
[[ 6  8]
 [10 13]]

2. x - y =
[[-4 -4]
 [-4 -3]]

3. x * 3 =
[[ 3  6]
 [ 9 15]]

4. Square of each element of x (np.square):
[[ 1  4]
 [ 9 25]]

5a. Dot product v · w = 219

5b. Dot product x · v =
[29 77]

5c. Dot product x · y =
[[19 22]
 [50 58]]

6a. Concatenate x and y along rows (axis=0 / vstack):
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

6b. Concatenate v and w along column (column_stack):
[[ 9 11]
 [10 12]]

7. Trying np.concatenate((x, v))...
   ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

   WHY: x has shape (2, 2) (2D) but v has shape (2,) (1D).
   np.concatenate() requires ALL arrays to have the same number of dimensions.
   Since x is 2-dimensional and v is 1-dimensional, they are incompatible.

   FIX: reshape v to (1, 2) first, then concatenate a

### Problem 4: Matrix Operations

In [27]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

print("A =")
print(A)
print("B =")
print(B)
print()

# ── Proof 1: A · A⁻¹ = I ──────────────────────────────────────────────────
A_inv = np.linalg.inv(A)
A_times_Ainv = np.dot(A, A_inv)

print("PROOF 1: A · A⁻¹ = I")
print("A⁻¹ =")
print(A_inv)
print("A · A⁻¹ =")
print(np.round(A_times_Ainv, decimals=10))
print("Confirmed (np.allclose):", np.allclose(A_times_Ainv, np.eye(2)))
print()

# ── Proof 2: AB ≠ BA ──────────────────────────────────────────────────────
AB = np.dot(A, B)
BA = np.dot(B, A)

print("PROOF 2: AB ≠ BA")
print("AB =")
print(AB)
print("BA =")
print(BA)
print("AB == BA?", np.array_equal(AB, BA), "  →  Matrix multiplication is NOT commutative.")
print()

# ── Proof 3: (AB)ᵀ = BᵀAᵀ ───────────────────────────────────────────────
AB_T  = AB.T
BT_AT = np.dot(B.T, A.T)

print("PROOF 3: (AB)ᵀ = BᵀAᵀ")
print("(AB)ᵀ =")
print(AB_T)
print("Bᵀ · Aᵀ =")
print(BT_AT)
print("Equal:", np.array_equal(AB_T, BT_AT))


A =
[[3 4]
 [7 8]]
B =
[[5 3]
 [2 1]]

PROOF 1: A · A⁻¹ = I
A⁻¹ =
[[-2.    1.  ]
 [ 1.75 -0.75]]
A · A⁻¹ =
[[1. 0.]
 [0. 1.]]
Confirmed (np.allclose): True

PROOF 2: AB ≠ BA
AB =
[[23 13]
 [51 29]]
BA =
[[36 44]
 [13 16]]
AB == BA? False   →  Matrix multiplication is NOT commutative.

PROOF 3: (AB)ᵀ = BᵀAᵀ
(AB)ᵀ =
[[23 51]
 [13 29]]
Bᵀ · Aᵀ =
[[23 51]
 [13 29]]
Equal: True


#### Solving the System of Linear Equations
```
2x - 3y + z  = -1
 x -  y + 2z = -3
3x +  y - z  =  9
```

In [28]:
# Represent the system AX = B as NumPy arrays
A_sys = np.array([[ 2, -3,  1],
                  [ 1, -1,  2],
                  [ 3,  1, -1]], dtype=float)

B_sys = np.array([-1, -3, 9], dtype=float)

print("System of equations:  AX = B")
print("A =")
print(A_sys)
print("B =", B_sys)
print()

# ── Method 1: Inverse method  X = A⁻¹ · B ────────────────────────────────
A_sys_inv = np.linalg.inv(A_sys)
X_inv = np.dot(A_sys_inv, B_sys)

print("METHOD 1 — Inverse method (X = A⁻¹ · B):")
print(f"  x = {X_inv[0]:.4f}")
print(f"  y = {X_inv[1]:.4f}")
print(f"  z = {X_inv[2]:.4f}")
print()

# ── Method 2: np.linalg.solve ────────────────────────────────────────────
X_solve = np.linalg.solve(A_sys, B_sys)

print("METHOD 2 — np.linalg.solve:")
print(f"  x = {X_solve[0]:.4f}")
print(f"  y = {X_solve[1]:.4f}")
print(f"  z = {X_solve[2]:.4f}")
print()

# ── Verification ──────────────────────────────────────────────────────────
print("Verification — A · X_solve:")
print(" ", np.round(np.dot(A_sys, X_solve), 6))
print("Expected B:")
print(" ", B_sys)


System of equations:  AX = B
A =
[[ 2. -3.  1.]
 [ 1. -1.  2.]
 [ 3.  1. -1.]]
B = [-1. -3.  9.]

METHOD 1 — Inverse method (X = A⁻¹ · B):
  x = 2.0000
  y = 1.0000
  z = -2.0000

METHOD 2 — np.linalg.solve:
  x = 2.0000
  y = 1.0000
  z = -2.0000

Verification — A · X_solve:
  [-1. -3.  9.]
Expected B:
  [-1. -3.  9.]


---
## 10.2 Experiment: How Fast is NumPy?
> Run each cell to measure and compare Python vs NumPy performance.

In [29]:
import time
import numpy as np

SIZE = 1_000_000

# Prepare data
py_a = list(range(SIZE))
py_b = list(range(SIZE))
np_a = np.arange(SIZE, dtype=float)
np_b = np.arange(SIZE, dtype=float)

print(f"Data prepared: two arrays/lists of size {SIZE:,} each.")


Data prepared: two arrays/lists of size 1,000,000 each.


In [30]:
# ── 1. Element-wise Addition ─────────────────────────────────────────────────
print("=" * 50)
print("1. ELEMENT-WISE ADDITION  (size = 1,000,000)")
print("=" * 50)

# Python list
start = time.time()
result_py = [py_a[i] + py_b[i] for i in range(SIZE)]
py_time = time.time() - start
print(f"  Python List : {py_time:.5f} seconds")

# NumPy
start = time.time()
result_np = np_a + np_b
np_time = time.time() - start
print(f"  NumPy Array : {np_time:.5f} seconds")
print(f"  Speedup     : {py_time / np_time:.1f}x faster with NumPy")


1. ELEMENT-WISE ADDITION  (size = 1,000,000)
  Python List : 0.07257 seconds
  NumPy Array : 0.00257 seconds
  Speedup     : 28.3x faster with NumPy


In [31]:
# ── 2. Element-wise Multiplication ───────────────────────────────────────────
print("=" * 50)
print("2. ELEMENT-WISE MULTIPLICATION  (size = 1,000,000)")
print("=" * 50)

# Python list
start = time.time()
result_py = [py_a[i] * py_b[i] for i in range(SIZE)]
py_time = time.time() - start
print(f"  Python List : {py_time:.5f} seconds")

# NumPy
start = time.time()
result_np = np_a * np_b
np_time = time.time() - start
print(f"  NumPy Array : {np_time:.5f} seconds")
print(f"  Speedup     : {py_time / np_time:.1f}x faster with NumPy")


2. ELEMENT-WISE MULTIPLICATION  (size = 1,000,000)
  Python List : 0.07884 seconds
  NumPy Array : 0.00211 seconds
  Speedup     : 37.4x faster with NumPy


In [32]:
# ── 3. Dot Product ────────────────────────────────────────────────────────────
print("=" * 50)
print("3. DOT PRODUCT  (size = 1,000,000)")
print("=" * 50)

# Python list
start = time.time()
dot_py = sum(py_a[i] * py_b[i] for i in range(SIZE))
py_time = time.time() - start
print(f"  Python List : {py_time:.5f} seconds")

# NumPy
start = time.time()
dot_np = np.dot(np_a, np_b)
np_time = time.time() - start
print(f"  NumPy Array : {np_time:.5f} seconds")
print(f"  Speedup     : {py_time / np_time:.1f}x faster with NumPy")


3. DOT PRODUCT  (size = 1,000,000)
  Python List : 0.06823 seconds
  NumPy Array : 0.00080 seconds
  Speedup     : 85.2x faster with NumPy


In [33]:
# ── 4. Matrix Multiplication (1000x1000) ──────────────────────────────────────
import random

MAT = 1000
print("=" * 50)
print(f"4. MATRIX MULTIPLICATION  ({MAT}x{MAT})")
print("=" * 50)

# Python lists
mat_py_a = [[random.random() for _ in range(MAT)] for _ in range(MAT)]
mat_py_b = [[random.random() for _ in range(MAT)] for _ in range(MAT)]

start = time.time()
result_mat_py = [
    [sum(mat_py_a[i][k] * mat_py_b[k][j] for k in range(MAT)) for j in range(MAT)]
    for i in range(MAT)
]
py_time = time.time() - start
print(f"  Python List : {py_time:.5f} seconds")

# NumPy
mat_np_a = np.random.random((MAT, MAT))
mat_np_b = np.random.random((MAT, MAT))

start = time.time()
result_mat_np = np.dot(mat_np_a, mat_np_b)
np_time = time.time() - start
print(f"  NumPy Array : {np_time:.5f} seconds")
print(f"  Speedup     : {py_time / np_time:.1f}x faster with NumPy")


4. MATRIX MULTIPLICATION  (1000x1000)
  Python List : 105.76174 seconds
  NumPy Array : 0.04913 seconds
  Speedup     : 2152.5x faster with NumPy
